### PR TITLE
Make changes and update

### PR DESCRIPTION
**Pull request by Ghilain**
### Project requirements

- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.

**Integration specs**

- Use Capybara to write integration tests for each view in your project.
- User index page
- user show page
  
- User post index page
  
- Post show page

**Be sure to include integration specs for any other features you may have implemented!**

## Testing
This command will run all the tests in your terminal:

> rspec spec

### CODE REVIEW

**Review by julie-ify — COMMENTED** [review]
Hi @Ghilain,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly ensure there are contributions from all partners on this project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ghilain** [comment]
Sorry @julie-ify there is a little issue but now solved

**Review by Davidosky007 — COMMENTED** [review]
Hi @Ghilain 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't show contribution from your partner as this is a paired programming activity you and your partners are expected to contribute codes to the project. and if by any means you were authorized by the student success to work solo on this project ? kindly add a screenshot to support this claim else you should work with your partner on this project thanks 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by brytebee — APPROVED** [review]
Hi, @Ghilain & @bizip👋,

##

### Highlights💡
- Commits were added by both partners as suggested by previous reviewers and required for collaborative milestones.✔️
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️
- All required specs and views have been tested.✔️
- All tests pass and are green.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 



Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghilain** [comment]
Thank you @brytebee

**Pull request merged**
